### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by cspollard** [lukasheinrich/pylhe#1]
Hello Lukas!

I copied this code into another repo. I hope that is ok, but I guess without an explicit license I am breaking the law somehow.

Want to add one so I am no longer a thief? ;-)

Chris

**Comment by lukasheinrich** [comment]
I went all in and did the entire shebang adding a license (i hope it's the right one? not a lawyer), code of conduct (behave!) and a zenodo DOI that you can cite :-p

glad it's useful for something

**Comment by cspollard** [comment]
woohoo! issue closed.

**Comment by lukasheinrich** [comment]
@cspollard as you can see the current code is a bit barebones, if you end up adding to it / make it nicer  in your other project (what is it?), it would be nice to add that back here. I'm sure there are tons of people trying to analyze LHE :)

**Comment by cspollard** [comment]
it's just a quick pheno study at the parton level before moving to particle -> reconstruction. I'll push anything back that I add, but for now it's perfectly adequate. Does the parsing stream btw? I am not sure if python's xml library does this by default.

**Comment by lukasheinrich** [comment]
yeah it should strem. the `ET.iterparse` returns a generator, so I thing running this on big files is fine (the example in the notebook was 10M events or so)
