### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by wiso** [lukasheinrich/pylhe#5]
Do you plan to support python3?

**Comment by shantanu-gontia** [comment]
@lukasheinrich this issue can be closed now

**Comment by lukasheinrich** [comment]
thanks @shantanu-gontia for the PR and @wiso for opening the issue. I'm happy people are using this package. If there is interest we could try to develop this into something more generally useful. @iamholger @cpollard

**Comment by shantanu-gontia** [comment]
@lukasheinrich I actually started outlining such a project. But due to other commitments couldn't really ossify it. Although, I'm very welcome to making this into a more general API for accessing LHE files.
