### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by ariaradick** [lukasheinrich/pylhe#7]
Hi, it appears that you may have updated this for Python 3, but I found an issue in __init__.py, line 19 should read "for k,v in kwargs.items():" rather than "for k,v in kwargs.iteritems():" in order to be compatible with Python 3. See the answer to [this stack exchange question.](https://stackoverflow.com/questions/8899129/how-do-i-loop-through-kwargs-in-python)

**Comment by lukasheinrich** [comment]
thanks! seems like @shantanu-gontia overlooked this, will fix when I get time (or feel free to submit a patch)

**Comment by matthewfeickert** [comment]
Seems like this can be closed as @ariaradick took care of this in https://github.com/lukasheinrich/pylhe/commit/95a4797f31c0dd1d5218c7e2c07d6ca507876941.
